package it.jonnysciar.web_ultraservizi.controllers;

import com.google.gson.Gson;
import it.jonnysciar.web_ultraservizi.entities.Persona;
import it.jonnysciar.web_ultraservizi.repositories.PersonaRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController // This means that this class is a Controller
@RequestMapping(path="/api") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PersonaRepository personaRepository;

    @PostMapping(path="/addPersona") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String name, @RequestParam String surname, @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Persona persona = new Persona();
        persona.setNome(name);
        persona.setCognome(surname);
        persona.setEmail(email);
        personaRepository.save(persona);
        return "Saved";
    }

    @GetMapping(path="/allPersone")
    public String getAllUsers() {
        // This returns a JSON or XML with the users
        return new Gson().toJson(personaRepository.findAll());
    }

    @GetMapping("/dadjokes")
    public String dadJokes() {
        return "Justice is a dish best served cold, if it were served warm it would be just water.";
    }
}